name: Build

on: 
  push:
    branches-ignore:
      - 'release'
    paths-ignore:
      - "**.md"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
          cache: true
          cache-dependency-path: .
        
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build
        run: dotnet build LCOnlineFix
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          if-no-files-found: error
          path: .\LCOnlineFix\bin\Debug\Debug\net35\LCOnlineFix.dll
